locations:
  - name: Washington Monument
    latitude: 38.8895
    longitude: -77.0352

influxdb:
  host: http://localhost:8086
  user: user
  password: password
  database: forecast

forecast:
  measurement_name: forecast

astronomy:
  enabled: yes
  measurement_name: astronomy

sources:
  enabled:
    - nws
    - visualcrossing
  visualcrossing:
    key: your_key_here

http_cache_dir: /var/lib/forecastmetrics/cache
state_dir: /var/lib/forecastmetrics/state